import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CheckBox } from "@mui/icons-material";
import Header from "./components/header";
import Nav from "./components/nav";
import About from "./components/about";
import Footer from "./components/footer";
import Contact from "./components/contact";
import ThemeProvider from "./provider";
import ThemeToggle from "./components/ThemeToggle";
import loadData from "./loadJsonData/loadData";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};




export default async function RootLayout({ children }) {
  const res = await loadData();
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        
      >
        <ThemeProvider>
          <Header header={res.header} /> 
          <Nav nav={res.nav}/>
          <About about={res.about}/>
          {children}
          <Contact contact={res.contact}/>
          <Footer footer={res.footer}/>
          <ThemeToggle />
        </ThemeProvider>
        
      </body>
    </html>
  );
}
